#!/usr/bin/env python3
 
import colors as c
import time

while True:
    for count in range(4):
        for count in range(11):
            print('badgers')
            time.sleep(0.38)

    for count in range(2):
            print('muuusssshrooom')
            time.sleep(0.8)

