#!/usr/bin/env python3

import colors as c

print('hello what is your name' + c.reset)

name = input(">>> ")

if name == 'Jason':

    print(c.red + 'thats my name cool' + c.reset)

else:
    print(c.blue + 'nice name just joking' + c.reset)
