#!/usr/bin/env python3

text = '''
I enjoy long, {noun1} in my {noun2}. I got sucked in to The forest.
ther are mean {noun3} and my  favrit type of {noun4} you die sorry.
You thot I wood make it so short ha. this story is {emotion}.

'''

words = {
    "noun1" : {},
    "noun2" : {},
    "noun3" : {},
    "noun4" : {},
    "emotion" : {},
}

print(c.clear + c.red + '''
Welcome 
''' + c.reset 

answer = {}
for key in words:
    desc = 
    
