#!/usr/bin/env python3

import colors as c

print(c.clear + c.yellow + ''''
Who would cross the bridge of Death
Must answer me these guestions three
'Ere the other side he see.
''' + c.reset) 

def prompt(question):
    print(question )
    answer = input('> ' + c.base3).lower().strip()
    print(c.reset)
    return answer 

def live():
    print(c.green + "Right, off you go then." + c.reset)

def die():
    print(c.red + "Thou art cast into the Gorge of Eternal peril" + c.reset)
name = prompt(c.red + 'What is your name?' + c.reset)
quest = prompt(c.red + 'What is your quest?' + c.reset)

if name in ['lancelot','galahad']:
    color = prompt(c.blue + 'What is your favorite color?'+ c.reset) 
    if color == 'blue':
        live()
    else:
        die()

elif name == 'robin':
    capital = prompt(c.blue + 'what is the capital of assyria?' + c.reset)
    if capital in ['assur','ashur']:
        live()
    else:
        die()

elif name == 'arthur': 
    speed = prompt(c.red + 'what is the air speed velocity of anladen swallow?' + c.reset)
    if speed in ['24mph','african or european']: 
        live()
    elif speed == 'what do you mean an african or european swallow?':
        print('The Bridgekeeper is thrown into the Gorge of Eternal peril')
        live()
    else:
        die() 
