#!/usr/bin/env python3

import colors as c
import minecraft as quiz
import random

print(c.clear + quiz.intro) 

while quiz.questions:
    questions_function =
    if random.choice(quiz.questions)
    if questions_function():
    else:
        print('right man')



