#!/usr/bin/env python3

import colors as c
from utils import ask

print(c.clear + c.blue + '''
welcome to qgame1
''')

answer = ask('how many daimonds does it take to make a gold pickaxe')

if answer == (" 'zero','0','none')

